# $FreeBSD: head/devel/rubygem-hocon/Makefile 447828 2017-08-12 13:20:51Z romain $

PORTNAME=	hocon
PORTVERSION=	1.2.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	puppet@FreeBSD.org
COMMENT=	Ruby port of the Typesafe Config library

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem
USE_RUBY=	yes

PLIST_FILES=	bin/hocon

.include <bsd.port.mk>
