# $FreeBSD$

PORTNAME=	hocon
PORTVERSION=	1.2.5
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	romain@FreeBSD.org
COMMENT=	A Ruby port of the Typesafe Config library

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_RUBY=	yes
USES=		gem

PLIST_FILES=	bin/hocon

.include <bsd.port.mk>
